# -*- coding: utf-8 -*-
"""Prodigy_Infotech_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O3nnQlqSQAB4O8Ehc-OboootEoeGeIl-
"""

#@title imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

#@title acquiring data
data = pd.read_csv('/content/drive/MyDrive/Mall_Customers.csv')
data.head()

data.describe()

plt.scatter(data['Annual Income (k$)'], data['Spending Score (1-100)'])
plt.show()

from sklearn.preprocessing import LabelEncoder
print(data.isnull().sum())
customers_data = data.iloc[:,[3,4]].values
label_encoder = LabelEncoder()
data['Gender'] = label_encoder.fit_transform(data['Gender'])
data.head()

#@title # finding wcss value (Within Clusters Sum of Squares)
from sklearn import preprocessing

# Assuming 'data' is your original DataFrame
data_scaled = preprocessing.scale(data.iloc[:, [3, 4]])

kmeans = KMeans(2)
kmeans.fit(data_scaled)

clusters = pd.DataFrame(data_scaled, columns=['Feature1', 'Feature2'])
clusters['Cluster_pred'] = kmeans.fit_predict(data_scaled)

WCSS = []

for i in range(1, 10):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(data_scaled)
    WCSS.append(kmeans.inertia_)

#@title plot elbow graph

sns.set()
plt.plot(range(1,10), WCSS)
plt.title('The Elbow Point Graph')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

#@title plotting all the clusters
# The result was 3,5 which means we're gonna try these values each for the k of the clusters

kmeans_new = KMeans(5)
kmeans_new.fit(data_scaled)
clusters_new = data.copy()

clusters_new['Cluster_pred'] = kmeans_new.fit_predict(data_scaled)
# print(clusters_new)

plt.scatter(clusters_new['Annual Income (k$)'], clusters_new['Spending Score (1-100)'], c=clusters_new['Cluster_pred'], cmap='rainbow')
plt.title('Customer Groups')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.show()